// <auto-generated />
namespace AMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changes30March : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes30March));
        
        string IMigrationMetadata.Id
        {
            get { return "202403300654387_changes30March"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
